<%
Option Explicit
Dim i, total, userName, html
total = 0
userName = "guest"
%>
<!doctype html>
<html>
<head>
    <title>Legacy ASP Smoke Fixture</title>
</head>
<body>
<h1>Dashboard</h1>
<ul>
<%
For i = 1 To 60
    total = total + i
%>
    <li>Item <%= i %> sum=<%= total %></li>
<%
Next
%>
</ul>

<%
Function RenderRow(label, value)
    Response.Write "<tr><th>" & label & "</th><td>" & value & "</td></tr>"
End Function
%>

<table border="1">
<%
Call RenderRow("User", userName)
Call RenderRow("Total", total)
%>
</table>

<%
If total > 1000 Then
    Response.Write "<p>Large total</p>"
Else
    Response.Write "<p>Small total</p>"
End If
%>

<%
' Simulate mixed legacy constructs
Dim arr(5)
arr(0) = "A"
arr(1) = "B"
arr(2) = "C"
arr(3) = "D"
arr(4) = "E"
arr(5) = "F"
%>

<ol>
<%
For i = 0 To 5
%>
    <li><%= arr(i) %></li>
<%
Next
%>
</ol>

<%
Class LegacyUser
    Public Name
    Public Function AsText()
        AsText = "User: " & Name
    End Function
End Class

Dim u
Set u = New LegacyUser
u.Name = userName
Response.Write "<pre>" & u.AsText() & "</pre>"
%>

<%
Dim c
For c = 1 To 40
    html = "<div class=""block"">block-" & c & "</div>"
%>
    <%= html %>
<%
Next
%>

<%
Select Case LCase(userName)
    Case "admin"
        Response.Write "<p>mode=admin</p>"
    Case "guest"
        Response.Write "<p>mode=guest</p>"
    Case Else
        Response.Write "<p>mode=other</p>"
End Select
%>

<%
On Error Resume Next
Dim obj
Set obj = Server.CreateObject("Scripting.Dictionary")
If Err.Number <> 0 Then
    Response.Write "<p>CreateObject failed</p>"
Else
    obj.Add "k1", "v1"
    obj.Add "k2", "v2"
    Response.Write "<p>user=" & userName & "</p>"
    Response.Write "<p>dict=" & obj.Count & "</p>"
End If
%>

<%-- ASP comment scriptlet must not be injected --%>

<footer>
    Generated by test fixture
</footer>
</body>
</html>
