{
  parserClass="dvamuch.aspclassiclanguagesupport2.lang.vbscript.parser.VbScriptParser"
  psiClassPrefix="Vb"
  psiImplClassSuffix="Impl"
  psiPackage="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi"
  psiImplPackage="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi.impl"
  elementTypeHolderClass="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi.VbTypes"
  tokenTypeClass="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi.VbTokenType"
  elementTypeClass="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi.VbElementType"
  generateVisitor=true
}

vbFile ::= statement_list?

statement_list ::= (stmt_separator | template_gap | statement)+
stmt_separator ::= EOL | COLON
private template_gap ::= ASP_OPEN | ASP_CLOSE | ASP_TEMPLATE_DATA | ASP_CONTROL

statement ::=
    option_stmt
  | comment_stmt
  | const_stmt
  | dim_stmt
  | visibility_stmt
  | class_stmt
  | function_stmt
  | sub_stmt
  | property_stmt
  | if_stmt
  | select_stmt
  | for_stmt
  | foreach_stmt
  | do_stmt
  | while_stmt
  | with_stmt
  | exit_stmt
  | on_error_stmt
  | redim_stmt
  | erase_stmt
  | execute_stmt
  | asp_output_stmt
  | assignment_stmt
  | call_stmt
  | expr_stmt

option_stmt ::= OPTION EXPLICIT

visibility_stmt ::= (PUBLIC_KW | PRIVATE_KW) DEFAULT? (function_stmt | sub_stmt | property_stmt | visibility_var_decl)
visibility_var_decl ::= var_decl (COMMA var_decl)*

const_stmt ::= CONST const_decl (COMMA const_decl)*
const_decl ::= id EQ expr

dim_stmt ::= DIM var_decl (COMMA var_decl)*
var_decl ::= id (LPAREN (expr (COMMA expr)*)? RPAREN)?

class_stmt ::= CLASS id stmt_separator+ class_body? END CLASS
class_body ::= statement_list

function_stmt ::= FUNCTION id param_list? declaration_block_start+ statement_list? END FUNCTION
sub_stmt ::= SUB id param_list? declaration_block_start+ statement_list? END SUB
property_stmt ::= PROPERTY (GET | LET | SET) id param_list? declaration_block_start+ statement_list? END PROPERTY
private declaration_block_start ::= stmt_separator | ASP_CLOSE

param_list ::= LPAREN (param (COMMA param)*)? RPAREN
param ::= (BYVAL | BYREF)? (OPTIONAL)? id (EQ expr)?

if_stmt ::= if_block_stmt | if_single_line_stmt
if_block_stmt ::= IF expr THEN if_block_start statement_list? elseif_block* else_block? END IF
private if_block_start ::= COMMENT? block_start stmt_separator*
private block_start ::= EOL | ASP_CLOSE
if_single_line_stmt ::= IF expr THEN inline_if_branch? (ELSE inline_if_branch?)? (COLON? END IF)?
inline_if_branch ::= statement (COLON statement)*
if_block_branch ::= stmt_separator+ statement_list? | statement_list
elseif_block ::= ELSEIF expr THEN if_block_branch?
else_block ::= ELSE if_block_branch?

select_stmt ::= SELECT CASE expr select_case_start case_block* case_else_block? END SELECT
private select_case_start ::= (stmt_separator | comment_stmt | template_gap)*
case_block ::= CASE case_expr_list stmt_separator* statement_list?
case_else_block ::= CASE ELSE stmt_separator* statement_list?
case_expr_list ::= case_expr (COMMA case_expr)*
case_expr ::= expr | (IS rel_op expr)

for_stmt ::= FOR id EQ expr TO expr (STEP expr)? stmt_separator* statement_list? NEXT id?
foreach_stmt ::= FOR EACH id IN expr stmt_separator* statement_list? NEXT id?

do_stmt ::= DO (WHILE | UNTIL)? expr? stmt_separator* statement_list? LOOP (WHILE | UNTIL)? expr?
while_stmt ::= WHILE expr stmt_separator* statement_list? WEND

with_stmt ::= WITH expr stmt_separator* statement_list? END WITH

exit_stmt ::= EXIT (FUNCTION | SUB | PROPERTY | FOR | DO)

on_error_stmt ::= ON ERROR RESUME NEXT | ON ERROR GOTO NUMBER

redim_stmt ::= REDIM (PRESERVE)? redim_decl (COMMA redim_decl)*
redim_decl ::= id LPAREN expr (COMMA expr)* RPAREN

erase_stmt ::= ERASE id (COMMA id)*

execute_stmt ::= (EXECUTE | EXECUTEGLOBAL) expr

asp_output_stmt ::= ASP_EXPR_OPEN expr EOL* ASP_CLOSE

assignment_stmt ::= (SET | LET)? lvalue EQ expr
lvalue ::= postfix_ref_expr | with_member_ref_expr

call_stmt ::= CALL? (qualified_identifier | with_qualified_identifier) (bare_call_args | call_args)?
call_args ::= LPAREN call_arg_list? RPAREN
call_arg_list ::= call_arg (COMMA call_arg)*
call_arg ::= expr?
bare_call_args ::= COMMA call_arg (COMMA call_arg)* | expr (COMMA call_arg)*

expr_stmt ::= expr

expr ::= or_expr
or_expr ::= and_expr ((OR | XOR | EQV | IMP) and_expr)*
and_expr ::= not_expr (AND not_expr)*
not_expr ::= (NOT)* compare_expr
compare_expr ::= concat_expr ((EQ | NEQ | LT | GT | LE | GE | IS) concat_expr)*
concat_expr ::= add_expr (AMP add_expr)*
add_expr ::= mult_expr ((PLUS | MINUS) mult_expr)*
mult_expr ::= pow_expr ((STAR | SLASH | IDIV | MOD) pow_expr)*
pow_expr ::= unary_expr (POW unary_expr)*
unary_expr ::= (PLUS | MINUS) unary_expr | primary_expr

primary_expr ::= literal | postfix_ref_expr | with_member_ref_expr | grouped_expr | new_expr
private grouped_expr ::= LPAREN expr RPAREN postfix_suffix*
private new_expr ::= NEW qualified_identifier postfix_suffix*
postfix_ref_expr ::= id postfix_suffix*
with_member_ref_expr ::= DOT id postfix_suffix*
postfix_suffix ::= DOT id | call_args
qualified_identifier ::= id (DOT id)*
with_qualified_identifier ::= DOT id (DOT id)*

literal ::= NUMBER | FLOAT | HEX_NUMBER | OCT_NUMBER | STRING | DATE | TRUE | FALSE | NULL | EMPTY | NOTHING
id ::= IDENTIFIER {mixin="dvamuch.aspclassiclanguagesupport2.lang.vbscript.psi.impl.VbIdMixin"}

comment_stmt ::= COMMENT

rel_op ::= EQ | NEQ | LT | GT | LE | GE
